### PR TITLE
Created a Our Team Page

### PR DESCRIPTION
**Pull request by nikhil25803**
## 👨‍💻 Changes proposed

This is the pull request regarding issue #250 
I created a Our Team page that fetch data from JSON file and dynamically generate profile card on updating the JSON file.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Separate JSON files have been created for Owner, Mentor, Video Creators, Content Writers, Web Developers and Top Contributors in the static folder of this repo.
Profile cards are generated dynamically on updating JSON file of each.
Added Our Team tab in the navbar section.

#### Overview
Overview

#### JSON Files
JSON Files

#### JSON file example
JSON File Example

### CODE REVIEW

**Comment by arpit456jain** [comment]
@nikhil25803 meanwhile can u work on the UI improvement

**Comment by nikhil25803** [comment]
@arpit456jain I was going with the UI format of the website, even the cards in pricing section are minimal and similar to the profile card I created.

**Comment by arpit456jain** [comment]
> @arpit456jain I was going with the UI format of the website, even the cards in pricing section are minimal and similar to the profile card I created.

yeah no problem

**Comment by nikhil25803** [comment]
@singhmansi25 , @raghavTinker , @KKhushhalR2405 .... Can you please review and merge it?

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain. We just need to look out for a way to fill in the proper details.

**Comment by nikhil25803** [comment]
By updating the respective json file changes will be shown on the website. I have added few just for testing

**Comment by KKhushhalR2405** [comment]
> 

That sounds good.

**Comment by arpit456jain** [comment]
@nikhil25803 i will provide u the data in next PR fill that data in json file

**Comment by nikhil25803** [comment]
> @nikhil25803 i will provide u the data in next PR fill that data in json file

Thank you ! So, do I need to open this as a new issue regarding updating the JSON file?

**Pull request merged**
