### PR TITLE
Adding new topics and edit old docs in CSS Course

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
### Adding 3 new topics and editing CSS Colors page

- CSS Comments
- CSS Borders
- CSS Box-Model &Outline

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review my PR @arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker

**Review by singhmansi25 — APPROVED** [review]
LGTM @arpit456jain 
Well done @muhammadgalhoum

**Comment by muhammadgalhoum** [comment]
I have added all videos and docs to the CSS Course please add a level @arpit456jain

**Pull request merged**
