### PR TITLE
Updating README.md file with the link of the CodingEasy repo

### PR DESCRIPTION
**Pull request by Muhammad-Galhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Issue #189 is regarding the links for GSSOC'22 in lines 36-44. You are supposed to change those links. Please do that

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
image

Also change GSSoC20 to GSSoC22

**Comment by Muhammad-Galhoum** [comment]
I have already replaced these links with this link https://gssoc.girlscript.tech/
Do you want other links? please put the right links here
@KKhushhalR2405

**Comment by KKhushhalR2405** [comment]
image
I am referring to these texts.

**Comment by Muhammad-Galhoum** [comment]
**Do you want me to change 20 to 22?** @KKhushhalR2405 
**Because I don't have any links for GSSoC'20 and can't find it**

**Comment by KKhushhalR2405** [comment]
> **Do you want me to change 2020 to 2022?** @KKhushhalR2405 **Because I don't have any links for GSSoC'20 and can't find it**

Yes

**Comment by Muhammad-Galhoum** [comment]
**I really wanted to change GSSoC20 to GSSoC22, but I thought that there are certain links for GSSoC20, and all that is required of me is to change the links only, not any text

In general, the required changes have already been made** @KKhushhalR2405

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain

**Review by singhmansi25 — APPROVED** [review]
Good work @Muhammad-Galhoum

**Comment by KKhushhalR2405** [comment]
Please add level tag to the PR @arpit456jain  @singhmansi25

**Pull request merged**
