### PR TITLE
Updated Readme.md file for UI enhancement

### PR DESCRIPTION
**Pull request by Chayan-11**
1. Fixed the alignment of the title "CodingEasy" to the center position.
2. Fixed the navigable links of table of contents.
3. Added the "Total Lines" badge, "Stars" badge, "Forks" badge, "Contributors", "Repo Size" and "last commit" badge for visitors to access the stats of the project.
4. Removed Emojis for better UI.

@arpit456jain Please review the changes and merge it if you find them suitable to be added to your project.

The sample Readme looks as follows:
CodingEasy Readme Sample

### CODE REVIEW

**Comment by arpit456jain** [comment]
On which issue you are working?

**Comment by Chayan-11** [comment]
> On which issue you are working?
I didn't create an issue but made the PR directly for updating the Readme

**Comment by Chayan-11** [comment]
And I'm making this contribution for SWoC

**Comment by arpit456jain** [comment]
From next time first make issue then PR

**Comment by Chayan-11** [comment]
> From next time first make issue then PR

Yeah sure I will do that. Do I need to make one for this ?

**Comment by arpit456jain** [comment]
No

**Pull request merged**
