### PR TITLE
Quiz page

### PR DESCRIPTION
**Pull request by nikhil25803**
## 👨‍💻 Changes proposed
This pull request is regarding #336. I made a Quiz Page as shown in the screenshot where user can test their skill. After every quiz, a result page is shown for the evaluation

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Added quiz tab in Navbar
[image](https://www.linkpicture.com/view.php?img=LPic628967490884e1779822245)

### Select the language you want to take a test of
[image](https://www.linkpicture.com/view.php?img=LPic628967490884e1779822245)

### Python demo quiz 
[image](https://www.linkpicture.com/view.php?img=LPic628967490884e1779822245)

### Result page
[image](https://www.linkpicture.com/view.php?img=LPic628967490884e1779822245)

### CODE REVIEW

**Comment by nikhil25803** [comment]
@singhmansi25 , @raghavTinker , @KKhushhalR2405 .. I have made the PR. Please do review it :)

**Review by singhmansi25 — CHANGES_REQUESTED** [review]
@nikhil25803 
The quiz already has options marked, instead make them unmarked initially.
Make an option to return to quiz after result is displayed. 
Try to add more QnA in Python Quiz

**Comment by nikhil25803** [comment]
@arpit456jain Bhaiya asked me to make the PR adding 5 questions of Python only, and update this PR making the changes requested

**Comment by singhmansi25** [comment]
@nikhil25803 
Make this change: The quiz already has options marked, instead make them unmarked initially.

**Comment by nikhil25803** [comment]
I have added the Back to Quiz Button 

[image](https://www.linkpicture.com/view.php?img=LPic628a20c99bd77341124672)

@singhmansi25 Please do review it

**Pull request merged**
