### PR TITLE
Improving the home page of the site as shown in the video

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## 🛠️ Fixes Issue #263 

**1. Add a drop-down list in each of the navbars for the blog and the website, each of them differs in some options**
**2. Show the profile picture of the person who is logged in to our site in the navbar**
**3. Improving course cards and making them more animated**
**4. Adding several distinctive images to the carousel**
**5. Add a link to your favourite posts on the profile page** 

https://user-images.githubusercontent.com/56798376/169346526-529b2ce5-85f2-4469-a64b-ef906d0ebbfb.mp4

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review my PR @arpit456jain @KKhushhalR2405 @raghavTinker @singhmansi25

**Comment by KKhushhalR2405** [comment]
@muhammadgalhoum It would be helpful if you mention the changes you have added.

**Review by raghavTinker — APPROVED** [review]

**Comment by muhammadgalhoum** [comment]
> It would be helpful if you mention the changes you have added.

I actually did that, as I made a video explaining the features that I added as well as those that I modified, and in order to know these features, you will find me moving the mouse pointer on them in the video
Also, I will write it here
1)
Add a drop-down list in each of the navbars
 For the blog and the website, each of them differs in some options
2)
Show the profile picture of the person who is logged in to our site in the navbar
3)
Improving course cards and making them more animated
4)
Adding several distinctive images to the carousel
5) Add a link to your favourite posts on the profile page

@KKhushhalR2405

**Comment by arpit456jain** [comment]
@muhammadgalhoum great i will merge when its approved 
actually the UI is very dull can you something of that in next PR or add dark mode in it

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum great i will merge when its approved actually the UI is very dull can you something of that in next PR or add dark mode in it
Thanks @arpit456jain 
The next step I was thinking of is adding a dark mode but please put a level 3 on this PR

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain. Great work @muhammadgalhoum

**Review by singhmansi25 — APPROVED** [review]
Great work @muhammadgalhoum

**Pull request merged**
