### PR TITLE
Loops added

### LINKED ISSUE #223: Adding Loops Topic in CPP Module
### Description

Loops topic is to be added in the CPP Module

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
Closes #223 

## 👨‍💻 Changes proposed
Loops section  added

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Jayanth-MKV** [comment]
Please add the label and review @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by arpit456jain** [comment]
@Jayanth-MKV please share some ss or videos of ur work so that we can review faster

**Comment by arpit456jain** [comment]
@Jayanth-MKV please share some ss or videos of ur work so that we can review faster

**Comment by arpit456jain** [comment]
@Jayanth-MKV please share some ss or videos of ur work so that we can review faster

**Comment by Jayanth-MKV** [comment]
#review @arpit456jain

**Review by singhmansi25 — APPROVED** [review]
LGTM
@arpit456jain 
Please check at your side

**Pull request merged**
