### PR TITLE
Improved UI of Website

### LINKED ISSUE #204: Improve UI of website
### Description

Improve UI of whole website in multiple PRs

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Anjuli08**
## 🛠️ Fixes Issue
Improved  navbar and homepage

Closes #204 

## 👨‍💻 Changes proposed
changed color theme and style of home page (including navbar and footer)
  

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
1)
ss1
2)
ss2

### CODE REVIEW

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Hi @Anjuli08, Can you please remove these additional things

image

**Comment by Anjuli08** [comment]
Yes I'll remove this for sure ...and also i don't know from where does it came here as i didn't add it

**Comment by Anjuli08** [comment]
I have updated one of the files...pls review

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
I can still see them. You need to remove both arrows and login button
image

**Comment by arpit456jain** [comment]
@Anjuli08

**Comment by Anjuli08** [comment]
> @Anjuli08 

I updated the file ...kindly review it

**Comment by arpit456jain** [comment]
@singhmansi25 can u review it

**Review by Anjuli08 — COMMENTED** [review]
I removed additional code from the file

**Review by KKhushhalR2405 — APPROVED** [review]
Good work @Anjuli08. LGTM @arpit456jain

**Pull request merged**
