### PR TITLE
Add new jQuery Course part1

### PR DESCRIPTION
**Pull request by Muhammad-Galhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Muhammad-Galhoum** [comment]
Can you please revise my issue? @KKhushhalR2405 @arpit456jain

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain

**Review by KKhushhalR2405 — APPROVED** [review]

**Review by KKhushhalR2405 — COMMENTED** [review]
Approved

**Comment by arpit456jain** [comment]
@Muhammad-Galhoum link the PR with issue

**Comment by Muhammad-Galhoum** [comment]
"this commit fixes #175 "

**Pull request merged**
