### PR TITLE
Rest of css videos

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
### Adding 11 videos to the CSS course on the following pages

- CSS Alignments
- CSS Colors
- CSS Margin
- CSS Padding

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review my PR @arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker

**Comment by arpit456jain** [comment]
@muhammadgalhoum all 55 completed ?

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum all 55 completed ?

No, I added only the videos which have docs in our website
@arpit456jain

**Comment by arpit456jain** [comment]
ok add all of them i will add the labels after all videos added

**Comment by muhammadgalhoum** [comment]
> ok add all of them i will add the labels after all videos added

Until now I added all new topics and videos
3 new topics and 29 video
@arpit456jain

**Pull request merged**
