### PR TITLE
Doing the task number one in the description of issue number #267

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## 🛠️ Fixes Issue #267 

**Don't forget to create 2 groups from the Django admin panel**
1. the first is called admin
2. the second is called publisher

## see the video carefully

https://user-images.githubusercontent.com/56798376/166884316-af322306-865f-4412-bd69-6a301f0feb61.mp4

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please, review this PR @arpit456jain  @KKhushhalR2405  @raghavTinker

**Comment by arpit456jain** [comment]
@muhammadgalhoum 

normal user can't make a post and can't access any post to update , delete  right ?

**Comment by muhammadgalhoum** [comment]
No, you asked me to work on the category and not the post. Please see the description of the problem well

The normal user can create a new post, edit it or delete it
@arpit456jain

**Comment by muhammadgalhoum** [comment]
What is the benefit of the user logging in to our site if he is prohibited from creating, modifying or deleting his posts? Since we do not have on our site yet the advantage of liking posts or commenting on them
@arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum bro u didn't get the project correctly . let me clear it with u
Its not a blogging service.
Blog is for the organization , 
1. there will be some people with a specific role who will have the access to make a post. 
2. admin have the rights to edit,update,delete any post
3. normal users can like post comment on it and can save it for later.

so please make changes according to these needs. 

once again we not providing blogging service to the users. 

make a new PR for this after ur PR of search is gets merged

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum bro u didn't get the project correctly . let me clear it with u Its not a blogging service. Blog is for the organization ,
> 
> 1. there will be some people with a specific role who will have the access to make a post.
> 2. admin have the rights to edit,update,delete any post
> 3. normal users can like post comment on it and can save it for later.
> 
> so please make changes according to these needs.
> 
> once again we not providing blogging service to the users.
> 
> make a new PR for this after ur PR of search is gets merged

**This is a new requirement that was not previously mentioned in the description of the problem
Please edit your problem description and put level3 on this PR**
@arpit456jain

**Pull request closed without merging**
