### PR TITLE
Added Authentication

### LINKED ISSUE #179: Create a functional authentication system
### Description

Add following features to the app-
1. login page
2. register page
3. login required to access courses
4. password reset functionality
5. contact us form

Note - 
I plan to completely change the login and contact us page of the current project as they lack uniformity with the website. 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by ephemeralshay**
## 🛠️ Fixes Issue
Closes #179 

## 👨‍💻 Changes proposed
1. login.html page should be in 'users' app and not in home app. It has been changed accordingly.
2. Newly created users will have their own profile page section where they can update their username, email and profile picture.
3. Unregistered (Guest) users cannot access courses until they create an account.
4. Admin Site Header was customized.

## 📄 Note to reviewers
1. I did not focus on styling the pages.

### CODE REVIEW

**Comment by KKhushhalR2405** [comment]
Hi @ephemeralshay, we want you to add authentication using the current login/signup template. And for the time being, we think it's not a good idea to have login required feature for viewing courses. Can you please remove that

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Login required feature not required for time being

**Comment by arpit456jain** [comment]
@ephemeralshay I m getting errors in virtualenv
@KKhushhalR2405 did it run in your system

**Comment by KKhushhalR2405** [comment]
> @ephemeralshay I m getting errors in virtualenv @KKhushhalR2405 did it run in your system

@arpit456jain Some modules might be missing. @ephemeralshay has not updated the requirements.txt file. Please do that @ephemeralshay

**Comment by ephemeralshay** [comment]
All points noted. I'll try working on that

**Comment by arpit456jain** [comment]
@ephemeralshay remove merge conflicts also

**Comment by ephemeralshay** [comment]
I'll revert all the changes soon

**Pull request closed without merging**
