### PR TITLE
Adding all the new HTML videos uploaded to YouTube

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review @arpit456jain @singhmansi25 @KKhushhalR2405

**Comment by muhammadgalhoum** [comment]
Please don't merge this PR  until I push the new updates as I discover there are new videos didn't upload yet @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum all done ?

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum all done ?

Now I will push now the updates
@arpit456jain

**Pull request merged**
