### PR TITLE
Added 4 video tutorials on Topic : Git and Github

### PR DESCRIPTION
**Pull request by Ultimateutkarsh11**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have added the following tutorials :
1. Introduction to Git and Github.
2. git status command
3. git add command
4. git init command

All the videos are edited and designed in order to make the content attractive.
Link to the Excel file : 
[video tutorials.xlsx](https://github.com/arpit456jain/CodingEasy/files/8550252/video.tutorials.xlsx)

## 📷 Screenshots
image
image
image

### CODE REVIEW

**Comment by arpit456jain** [comment]
hey @Ultimateutkarsh11  please mention the urls of ur videos here also

**Comment by Ultimateutkarsh11** [comment]
[video tutorials.xlsx](https://github.com/arpit456jain/CodingEasy/files/8550375/video.tutorials.xlsx)

**Comment by arpit456jain** [comment]
@Ultimateutkarsh11 cool they are great 
just  a suggestion
1. obs studio use kro record krna easy hoga and background noice bhi km hogi
2. avoid face recording try to explain in comuter screen only just like ur other videos

rest content is fine great work

**Review by arpit456jain — APPROVED** [review]

**Comment by Ultimateutkarsh11** [comment]
> @Ultimateutkarsh11 cool they are great just a suggestion
> 
> 1. obs studio use kro record krna easy hoga and background noice bhi km hogi
> 2. avoid face recording try to explain in comuter screen only just like ur other videos
> 
> rest content is fine great work

Duly noted sir . aage see dhyaan dunga in points ka

**Comment by Ultimateutkarsh11** [comment]
> how much time it takes to make these 4 videos ?

videos ban gayi thi 3 din pehle hi pull request pehli baar ki hai use samjhne main dikkat ho rahi thi isliye thoda time lag gaya .
1 video per day bana sakta hun

**Comment by arpit456jain** [comment]
> > how much time it takes to make these 4 videos ?
> 
> videos ban gayi thi 3 din pehle hi pull request pehli baar ki hai use samjhne main dikkat ho rahi thi isliye thoda time lag gaya . 1 video per day bana sakta hun

ok so i am giving lvl 3 since it takes a lot of time from now onwards it will be lvl 2 

i hope its fine 

if u think its taking time more then 4 hours let me know in PR description

**Comment by Ultimateutkarsh11** [comment]
Yes its fine . I will let you know in case any video takes time of more than 4 hrs .
Thanks for lvl3 :)

**Pull request merged**
