### PR TITLE
Added Colors to Cpp page

### PR DESCRIPTION
**Pull request by devesh-2002**
Issue #92 
 I have added few colors in the page.  Please merge the PR.
image
image

### CODE REVIEW

**Review by ankitapuri — APPROVED** [review]

**Comment by arpit456jain** [comment]
@devesh-2002 can you change the inline css to external css so that we can apply changes easily

**Comment by Snehaa1203** [comment]
@arpit456jain @ankitapuri  I am getting some errors, its saying some checks were not successful!
image
Should I merge this?

**Comment by arpit456jain** [comment]
yes u can merge when he complete the requested changes

**Comment by devesh-2002** [comment]
Should I close this one and create a new PR? @arpit456jain

**Comment by arpit456jain** [comment]
as you wish if you can do the changes in this PR the do it in this only

**Comment by arpit456jain** [comment]
@Snehaa1203 just check once the PR and then merge it

**Review by Snehaa1203 — COMMENTED** [review]
fine

**Comment by arpit456jain** [comment]
@Snehaa1203 @ankitapuri can you please confirm whether there is color in cpp course or not because its totally white in my system 
image

**Comment by ankitapuri** [comment]
@devesh-2002 we can't see background color please make a new PR.

**Pull request merged**
