### PR TITLE
Rebuilding the blog and adding many fantastic features

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## 🛠️ Fixes Issue #241 

# Adding the following features to the blog

- blog home
- category page (You can from it update, delete the category if you are the person who created it)
- Add post form, update post form
- page for all users contains his/her posts
- post details page
- navbar with all categories

https://user-images.githubusercontent.com/56798376/166122223-016b8dc1-fa75-4c53-a448-82d8f7bdc4f6.mp4

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
### Can you please review this PR @singhmansi25 @KKhushhalR2405

**Comment by arpit456jain** [comment]
@muhammadgalhoum resolve these merge conflicts

@raghavTinker @KKhushhalR2405 review this PR carefully

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum in this video only features of this PR is there or all combine ??

All blog features in one video

**Comment by arpit456jain** [comment]
> > @muhammadgalhoum in this video only features of this PR is there or all combine ??
> 
> All blog features in one video

ok @muhammadgalhoum resolve the conflicts i will merge

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum resolve these merge conflicts
> 
> @raghavTinker @KKhushhalR2405 review this PR carefully

Solved

**Pull request merged**
