### PR TITLE
Added Side Navbar

### PR DESCRIPTION
**Pull request by BabyElias**
## 👨‍💻 Changes proposed

Fixed the top navbar and added side navbar to all courses except Cpp (Still adding the side navbars actually, will be completed in an hour almost)

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

The side Navbar may not be responsive. I tried a lot but to no results. So, I would request the reviewers that once this PR is merged, please create a new issue for making the side navbar responsive and assign it to someone(I will not be able to take that up).Sorry for the inconvenience caused though.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@BabyElias ur work is great 

image
image

maintain the color scheme

introduction is not linked to home page. in every course introduction is link is broken
image

**Comment by arpit456jain** [comment]
@BabyElias instead of adding navbar in all course at once just make it perfect for one course and then in next RP add it in others

**Comment by BabyElias** [comment]
Done with all the files.

**Comment by BabyElias** [comment]
> @BabyElias instead of adding navbar in all course at once just make it perfect for one course and then in next RP add it in others

 I missed seeing this then. I am so sorry for it.<br><br>
1)About the color schemes, I believe there is some issue with the inheritance Sir because since I used the complete navbar code by copy pasting it without inheritance, the color schemes for all are same in my system.


image
image

<br><br>
2)About the broken Links, that's because I have simply added the .HTML file in a href without the file path as I didn't know how you had linked the URLs using<br>
 "{% url 'ml1' %}?data=logregx"  such a format. In case you tell me that, I will link the homepages to the right page.

**Comment by BabyElias** [comment]
This is the reason behind the tables page
tempsnip

**Comment by arpit456jain** [comment]
hey @BabyElias  i understand ur problem 

first do one thing remove changes from all other courses except one who has less no of files 

so that we can review it and merge it with lvl 3

**Comment by BabyElias** [comment]
Ok @arpit456jain . I will create a New PR and then begin with the course having least number of files.

**Comment by KKhushhalR2405** [comment]
> Ok @arpit456jain . I will create a New PR and then begin with the course having least number of files.

Choose any one course and proceed. And I noticed that use are using inline css. Can you please change that to external css.

**Pull request closed without merging**
