### PR TITLE
added 2  css videos of more than 5 min each

### PR DESCRIPTION
**Pull request by myhacktech**
lecture 7:css margins:https://drive.google.com/file/d/1svR-QXpDATi4yWDT6dgNE9WJWuzUyamp/view?usp=sharing
lecture 8 css padding:https://drive.google.com/file/d/1Lnu5RRrmN9j7_f9k58Dx1mqQTpR_qjDG/view?usp=sharing
Screenshot (404)
Screenshot (405)

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by KKhushhalR2405** [comment]
Hi @myhacktech, I can not see any modified file. In which file you added the links to the videos?

**Comment by myhacktech** [comment]
> Hi @myhacktech, I can not see any modified file. In which file you added the links to the videos?

in video tutorials folder,css excelsheet

**Comment by KKhushhalR2405** [comment]
image
I can just see 6 video links here

**Comment by myhacktech** [comment]
> image I can just see 6 video links here

sorry, i corrected it just now

**Pull request closed without merging**
