### PR TITLE
Made Home Page Responsive

### PR DESCRIPTION
**Pull request by Atif0604**
Made Home Page Responsive
Issue : #1 
@arpit456jain

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @arpit456jain Please review my PR

**Comment by arpit456jain** [comment]
hey @Atif0604 can u share the video

**Comment by Atif0604** [comment]
> hey @Atif0604 can u share the video

Yeah Sure

**Comment by Atif0604** [comment]
https://user-images.githubusercontent.com/64218887/146637723-6143dce0-d388-4a6c-9378-9bfd79d36c4f.mp4

Here the Video @arpit456jain

**Comment by arpit456jain** [comment]
cool @Atif0604  i will merge it soon as i got the info about labels of levels

**Comment by Atif0604** [comment]
> cool @Atif0604 i will merge it soon as i got the info about labels of levels

@arpit456jain you can merge it for now and whenever you get the labels you can label it
as i can move forward for the contribution to the project

**Comment by arpit456jain** [comment]
sure @Atif0604

**Pull request merged**
