### PR TITLE
Added 3 Apps

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @7saikat7 @arpit456jain 
Please review
Fix : #83

### CODE REVIEW

**Comment by Snehaa1203** [comment]
Looks fine, was this running on your local server?

**Comment by Atif0604** [comment]
> Looks fine, was this running on your local server?

for now its not running
i'm just adding a httpsresponse to it so that the app can run on server

**Comment by Atif0604** [comment]
@Snehaa1203 Now its running

**Comment by arpit456jain** [comment]
@Atif0604 do one thing make a new PR for the same issue and implement the sign up and login feature please i will increase the label to hard

**Comment by arpit456jain** [comment]
@Atif0604 do one thing make a new PR for the same issue and implement the sign up and login feature please i will increase the label to hard

**Comment by Atif0604** [comment]
> @Atif0604 do one thing make a new PR for the same issue and implement the sign up and login feature please i will increase the label to hard

But what happened with this PR??

**Pull request merged**
