### PR TITLE
Loops Module Added

### LINKED ISSUE #223: Adding Loops Topic in CPP Module
### Description

Loops topic is to be added in the CPP Module

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
## 🛠️ Fixes Issue
Loops section is added

Closes #223 

## 👨‍💻 Changes proposed
Loops section  added

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Jayanth-MKV resolve merge conflicts

**Comment by Jayanth-MKV** [comment]
done

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
1) Image is not rendering
image

2) Theory and code should be aligned side by side as in the below example

image

**Comment by Jayanth-MKV** [comment]
Review @KKhushhalR2405

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
Good that you made the proposed changes.
I will add the Level-2 tag.

**Review by singhmansi25 — APPROVED** [review]

**Comment by singhmansi25** [comment]
@arpit456jain 
Please check this PR once.

**Comment by arpit456jain** [comment]
LGTM 
@KKhushhalR2405 @raghavTinker ur views ?

**Comment by arpit456jain** [comment]
@Jayanth-MKV one PR is merged just now can u remove these conflicts

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
One more change is required. Can you please add the theory inside the jumbotron.
image
Only this intro part.



Example:
image

Rest looks good.

**Pull request closed without merging**
