### PR TITLE
Adding only 2 videos for testing the appearance

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review my PR @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by arpit456jain** [comment]
@muhammadgalhoum add a video

**Comment by arpit456jain** [comment]
@muhammadgalhoum  ur branch is 48 commits' behind i can't merge it until its update
because due to this we lost latest changes before also

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum add a video

screencapture-127-0-0-1-8000-git1-2022-05-23-21_09_06

**Comment by muhammadgalhoum** [comment]
> @muhammadgalhoum ur branch is 48 commits' behind i can't merge it until its update because due to this we lost latest changes before also


image

**Pull request merged**
