### PR TITLE
Added Code for ContactUS

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #90
Hey @arpit456jain Please Review

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Atif0604 please share a video

**Comment by Atif0604** [comment]
> @Atif0604 please share a video

I havent tested it as it was your gmail address for sending email

**Comment by arpit456jain** [comment]
Test it with your email and make a video after that remove your email and push it

**Comment by arpit456jain** [comment]
@Atif0604

**Comment by Atif0604** [comment]
> @Atif0604

I'm a stuck at a particular step in code at this moment and i'm trying to fix it

**Comment by arpit456jain** [comment]
Ok u can take help from @7saikat7 @Snehaa1203

**Pull request merged**
