### PR TITLE
Added Preloader to all Pages

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @arpit456jain 
Please Review
Fix : #6 

https://user-images.githubusercontent.com/64218887/148199539-cdedc101-cf56-407e-8246-0bd041b03f10.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ankitapuri @7saikat7  will pre loader on all pages will be ok?

**Comment by Atif0604** [comment]
> @ankitapuri @7saikat7 will pre loader on all pages will be ok?

I added it to all pages as on moving to different pages there was the straight load of pages which doesn't look good to me

**Comment by arpit456jain** [comment]
@Atif0604 please make a new PR and just comment out the html code of pre loader in all pages except home page we will use it in future when website is completed

**Comment by Atif0604** [comment]
sure

**Pull request merged**
