### PR TITLE
YouTube Video Embedded

### LINKED ISSUE #233: integrate a youtube section in pages
### Description

take reference from here 
https://codewithharry.com/videos/tailwind-course-in-hindi-1/

idea is let say user go to HTML->basic tags so on that page there will be some documentation / a video section and a editor for testing the code

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
## 🛠️ Fixes Issue

Closes #233 

## 👨‍💻 Changes proposed
 A section has been added where You tube videos can be embedded

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Jayanth-MKV** [comment]
label and review @arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
Why have embedded irrelevant video link?
Please change it.
And add video links to bottom of page or in middle section.
@arpit456jain 
Where the video file should be placed in the respective section?

**Review by singhmansi25 — CHANGES_REQUESTED** [review]
@Jayanth-MKV 
Please make suggested changes.

**Comment by Jayanth-MKV** [comment]
> @Jayanth-MKV Why have embedded irrelevant video link? Please change it. And add video links to bottom of page or in middle section. @arpit456jain Where the video file should be placed in the respective section?

I didnt get this. What is this adding video links to bottom of the page. @singhmansi25

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
You have embedded the video link below the grey box. Instead add them after the content on page ends, so that any user who visits the website, first goes through the concept and then watches video for better understanding.
Also, u have added the link of beluga channel, instead add link related to Git and Github.

**Comment by arpit456jain** [comment]
@Jayanth-MKV can you share a video how its looking and how its working 
and don't worry about video we will change the links later

**Comment by Jayanth-MKV** [comment]
@arpit456jain @singhmansi25 
Review

https://user-images.githubusercontent.com/93820457/162452615-321cc4de-4d7f-413e-9637-335510af7a00.mp4

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
Well done

**Review by singhmansi25 — APPROVED** [review]

**Comment by singhmansi25** [comment]
@arpit456jain 
Please look at this once

**Pull request merged**
