### PR TITLE
Added 2 videos on css Maths functions including calc(),max(),and min() functions

### PR DESCRIPTION
**Pull request by myhacktech**
L42:https://drive.google.com/file/d/1whT_3lgoF4_o_aCFNDn-wI4gFtSEKR8r/view?usp=sharing
L43:https://drive.google.com/file/d/1rl6UulsflkMEI7jelzhjaa-5QZik36j0/view?usp=sharing
Screenshot (456)

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@myhacktech the video is not opening please check

**Comment by arpit456jain** [comment]
image

**Comment by myhacktech** [comment]
> image

@arpit456jain actually videos  process for few minutes after uploading
and it opens after some time

**Comment by myhacktech** [comment]
> image

Sir i think,level is not assigned to me in this PR and it is merged also,there i did not received points for this

**Comment by arpit456jain** [comment]
> > image
> 
> Sir i think,level is not assigned to me in this PR and it is merged also,there i did not received points for this

done

**Comment by arpit456jain** [comment]
since this PR and the PR which just gets merged contains videos on 5-6 mins that's why i gave lvl2 to this and lvl1 to that

**Comment by myhacktech** [comment]
> since this PR and the PR which just gets merged contains videos on 5-6 mins that's why i gave lvl2 to this and lvl1 to that

ok sir

**Pull request merged**
