### PR TITLE
Add blog

### PR DESCRIPTION
**Pull request by ephemeralshay**
## 👨‍💻 Changes proposed
Closes part of Issue #139 

## 📄 Note to reviewers
1. Blog section prototype has been added.
2. When there are more than 5 blogs, pages will be automatically paginated.
3. CRUD Operations on Blogpost are possible.

However, Blogs section cannot be fully realized because there is no proper authentication system on the website yet.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ephemeralshay solve merge conflicts

**Comment by KKhushhalR2405** [comment]
Hi @ephemeralshay, We have added an auth system to the website. You can use it to add/update/filter blogs now.

**Comment by ephemeralshay** [comment]
You can pull this PR as of now, I'll work on it further as time permits.

**Comment by KKhushhalR2405** [comment]
> @KKhushhalR2405 You can pull this PR as of now, I'll work on it further as time permits.

@arpit456jain

**Review by singhmansi25 — APPROVED** [review]
Well done @ephemeralshay 
Please check this once @arpit456jain

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
