### PR TITLE
Updating users roles for our blog

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
### Don't forget to create 2 groups from the Django admin panel
**1. the first is called admin**
**2. the second is called visito**r

https://user-images.githubusercontent.com/56798376/167247407-e1f05b8a-2baf-4d6e-9c3e-dc319c11260a.mp4

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please, review my PR @arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker

**Comment by singhmansi25** [comment]
LGTM @arpit456jain 
Nice work @muhammadgalhoum
 **Keep it up**.

**Review by singhmansi25 — APPROVED** [review]
Impressive work @muhammadgalhoum

**Comment by muhammadgalhoum** [comment]
Thanks @singhmansi25

**Comment by arpit456jain** [comment]
@singhmansi25 did u run the code on local system ??

**Comment by arpit456jain** [comment]
image

i created 2 groups but i am unable to see any edit functionality 

@raghavTinker @KKhushhalR2405  kindly review it

**Comment by muhammadgalhoum** [comment]
> image
> 
> i created 2 groups but i am unable to see any edit functionality
> 
> @raghavTinker @KKhushhalR2405 kindly review it

**You should add the user to the admin group 
Watch the video from the first minute 11:55 to the end**

**Comment by arpit456jain** [comment]
> > image
> > i created 2 groups but i am unable to see any edit functionality
> > @raghavTinker @KKhushhalR2405 kindly review it
> 
> **You should add the user to the admin group Watch the video from the first minute 11:55 to the end**

@muhammadgalhoum instead of making  user admin can u make the role staff . because its not good if content writer  has the access of admin panel 

what's ur views @raghavTinker @KKhushhalR2405

**Comment by KKhushhalR2405** [comment]
> 
> @muhammadgalhoum instead of making user admin can u make the role staff . because its not good if content writer has the access of admin panel
> 
> what's ur views @raghavTinker @KKhushhalR2405

Yeah...that sounds logical

**Review by raghavTinker — APPROVED** [review]

**Comment by raghavTinker** [comment]
> > > image
> > > i created 2 groups but i am unable to see any edit functionality
> > > @raghavTinker @KKhushhalR2405 kindly review it
> > 
> > 
> > **You should add the user to the admin group Watch the video from the first minute 11:55 to the end**
> 
> @muhammadgalhoum instead of making user admin can u make the role staff . because its not good if content writer has the access of admin panel
> 
> what's ur views @raghavTinker @KKhushhalR2405

Yeah....it should work like this

**Comment by muhammadgalhoum** [comment]
> > > image
> > > i created 2 groups but i am unable to see any edit functionality
> > > @raghavTinker @KKhushhalR2405 kindly review it
> > 
> > 
> > **You should add the user to the admin group Watch the video from the first minute 11:55 to the end**
> 
> @muhammadgalhoum instead of making user admin can u make the role staff . because its not good if content writer has the access of admin panel
> 
> what's ur views @raghavTinker @KKhushhalR2405



### Can u explain more what u need? try to give me an example or video
### I want to tell you when the user signup to our website he automatically join to visitor group which means that he can't access the admin panel and can't change his role in our website and there is a way to change the admin panel IP when you upload the website on a server which means only the person who know the admin panel IP can access the admin panel if he has a admin role
### And you are only the admin who can post, update and delete any post or category

**Comment by arpit456jain** [comment]
@muhammadgalhoum for now i am merging this PR lets discuss this next PR but that will of of lvl1

**Pull request merged**
