### PR TITLE
Add editor

### PR DESCRIPTION
**Pull request by Vaishnavi1411**
## 🛠️ Fixes Issue
Add Editor for HTML,CSS and JS.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
open

### CODE REVIEW

**Review by Vaishnavi1411 — COMMENTED** [review]
Added editor.html

**Review by raghavTinker — APPROVED** [review]

**Comment by raghavTinker** [comment]
The code looks fine!

**Comment by singhmansi25** [comment]
@arpit456jain 
Why this PR is getting a Greetings check failed?

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Nice that you have made the proposed changes.
Now the UI looks better.

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Please add a button/hyperlink that redirects to the code editor.

**Comment by arpit456jain** [comment]
> @arpit456jain Why this PR is getting a Greetings check failed?

ignore it

**Comment by arpit456jain** [comment]
@Vaishnavi1411 do the requested changes

**Comment by arpit456jain** [comment]
@Vaishnavi1411 make a new PR when u r free

**Pull request closed without merging**
