### PR TITLE
Added Common CSS File

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #49 
Hey @ankitapuri @LegendSumeet Please Review

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Atif0604 can we add css for navbar and footer in it. Since its common in whole website

**Comment by Atif0604** [comment]
Navbar and footer at this time doesn't require any css
they are all done by the bootstrap classes
@arpit456jain

**Comment by arpit456jain** [comment]
Ok then we should remove this common css from all other css files right? @Atif0604

**Comment by Atif0604** [comment]
Yup We can do the replace for almost all files except for feature.css(it has 1 css class diff) and css-> basic.css(it has a 2 css class diff)

**Comment by arpit456jain** [comment]
Ok then do that we can check the project by its deploy preview 
https://deploy-preview-50--coding-easy.netlify.app
Just do one thing
Make changes one by one commit them and push them and check its hosted preview if everything fine then do this for other files

**Comment by Atif0604** [comment]
Sure

**Comment by Atif0604** [comment]
Hey @arpit456jain Can you please check about the failed checks
Is it good to go?

**Comment by arpit456jain** [comment]
There is a bug in Deployment check if its working fine local sys or not check every page responsiveness and push again

**Comment by Atif0604** [comment]
> There is a bug in Deployment check if its working fine local sys or not check every page responsiveness and push again

Yeah I have pushed for only 1 page 
In the local server it was good to go
@arpit456jain

so should do i for all at once?

**Comment by arpit456jain** [comment]
> > There is a bug in Deployment check if its working fine local sys or not check every page responsiveness and push again
> 
> Yeah I have pushed for only 1 page In the local server it was good to go @arpit456jain
> 
> so should i do it for all at once?

Yeah do it one more page and push it

**Comment by arpit456jain** [comment]
@Atif0604 come on discord channel

**Comment by Atif0604** [comment]
> @Atif0604 come on discord channel

Yeah i have replied to you on discord @arpit456jain

**Comment by Atif0604** [comment]
Hey @ankitapuri @LegendSumeet Please Review

**Comment by ankitapuri** [comment]
@arpit456jain it seems fine to me

**Comment by LegendSumeet** [comment]
yes its fine

**Pull request merged**
