### PR TITLE
Sheetal chouhan

### LINKED ISSUE #172: Adding Django Course
### Description

I want to add Django course in the courses section of the website  

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SheetalChouhan12**
## 🛠️ Fixes Issue

Close #172 

## 👨‍💻 Changes proposed

Added Django Course in CodingEasy which includes different sections.
These different sections are Basic, Environment, Models, Projects, Views, Templates, Authentication, URLs with their respective Html templates.

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by singhmansi25** [comment]
@SheetalChouhan12 
there are conflicts in files. Please resolve this issue.

**Comment by KKhushhalR2405** [comment]
> Hey, I tried to resolve the conflict files but it's showing already up to date with the Master branch. Don't know what to do next. Can someone tell me?

Are you using the correct upstream? Did you try pulling the latest code

**Comment by SheetalChouhan12** [comment]
> > Hey, I tried to resolve the conflict files but it's showing already up to date with the Master branch. Don't know what to do next. Can someone tell me?
> 
> Are you using the correct upstream? Did you try pulling the latest code

I did when I first setup code in local system back then It was showing up to date but now I pull latest code . It has changes , I will do it and then make a PR again .

**Comment by arpit456jain** [comment]
@SheetalChouhan12 resolve merge conflicts or make a new PR

**Comment by SheetalChouhan12** [comment]
> @SheetalChouhan12 resolve merge conflicts or make a new PR

Okay . Will make new PR

**Pull request closed without merging**
