### PR TITLE
Adding 14 videos to CSS course

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
### Adding 14 videos to the CSS course on the following pages

- Main page of CSS Course
- CSS Syntax
- CSS Selectors
- CSS Functions
- CSS Font Family

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@muhammadgalhoum share the SS so that we can review it faster

**Comment by muhammadgalhoum** [comment]
@arpit456jain  U forgot to add a level here!

**Pull request merged**
