### PR TITLE
Adding the right routes for the C course and some other changes in the description

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
### What I have done are

1. Adding the right routes for the C course 
2. Adding folders and files for the C and Cpp courses topics 
3. Updating the routes in the c.html and cpp.html files
4. Updating the views.py and urls.py in the home app
5. Adding the link for this course and C ++ course in the navbar

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review this PR @arpit456jain @KKhushhalR2405  @raghavTinker @singhmansi25

**Comment by muhammadgalhoum** [comment]
Please, Put level 3 here and I will update this PR asap @arpit456jain

**Comment by KKhushhalR2405** [comment]
I believe you are doing extra work apart from adding routes for the C course in this PR. I can see some changes in the blog folder. May I know the reason for it?

**Comment by muhammadgalhoum** [comment]
Because there were sub-topics without explanation or correct links, so I made primary pages for them, and the person responsible for completing this course is all I have to do is add the explanation only for each sub-topic @KKhushhalR2405

**Comment by muhammadgalhoum** [comment]
Please put level 3 on this PR as soon as possible so that I can update this PR as soon as possible. @arpit456jain

**Comment by KKhushhalR2405** [comment]
I believe #271 aimed to add routes for the already present templates.
image

You have not added routes for them but added more subtopics which was not mentioned and not needed.

**Comment by muhammadgalhoum** [comment]
**Yes, what is required of me in it is to add the correct paths to Course C, but on the main page “c.html” for Course C there are several links that do not have pages and when I click on them, an error will occur, so I made folders and files for these links, and I also set the course on the home.html page and add A picture of it and also writing the code for the course in both views.py and urls.py**

### Am I wrong that I do what is required of me in the best way? Or do you want someone to modify Kodi after writing it?


**Please look carefully at the files that I have changed and also the files that I have created**

@KKhushhalR2405

**Comment by muhammadgalhoum** [comment]
Now, you can re-review again @KKhushhalR2405 @arpit456jain 
And please put level 3 to this PR

**Comment by arpit456jain** [comment]
@muhammadgalhoum make sure any 2 mentors approve this PR tag them in discord or msg them

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain

**Pull request merged**
