### PR TITLE
Contact us form

### PR DESCRIPTION
**Pull request by Muhammad-Galhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Muhammad-Galhoum** [comment]
Can you please review this
@arpit456jain 
@KKhushhalR2405 
@raghavTinker 
@singhmansi25

**Comment by KKhushhalR2405** [comment]
@Muhammad-Galhoum Your previous pr #182 is not yet merged. PA will merge it soon. After that, this PR will be reviewed.  Thank you

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
image
Can you change the success msg to "Thank you for contacting us" please. And not in caps

**Review by KKhushhalR2405 — COMMENTED** [review]
Also, add template inheritance to the contact.html file. While being in the contact page, I could not see the navbar.

**Comment by Muhammad-Galhoum** [comment]
changes have been made,
You can check my code again @KKhushhalR2405

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
image

@Muhammad-Galhoum Can you please check why the orientation is disturbed?

**Comment by Muhammad-Galhoum** [comment]
@KKhushhalR2405 

## I think this problem exists on your device only 

## Please ask any other Reviewer To test the Code on his/her device

## The code worked on my device without any issue never

## I will attach an image for you and if u want a video please don't hesitate to tell me 

## screencapture-127-0-0-1-8000-2022-03-14-00_16_51

## And this is the Image for the solution of this issue #180 

## screencapture-127-0-0-1-8000-contact-2022-03-14-00_17_46

**Review by raghavTinker — APPROVED** [review]

**Comment by arpit456jain** [comment]
@Muhammad-Galhoum its giving me the error of csrf verifiation

**Comment by KKhushhalR2405** [comment]
> and the makemigrations command is not working

Yes. I am also looking for a solution to that issue.

You can use the following commands.
-> python manage.py makemigrations
-> python manage.py migrate --run-syncdb

Reference: https://ruddra.com/syncdb-vs-migration/

**Comment by KKhushhalR2405** [comment]
> @Muhammad-Galhoum its giving me the error of csrf verification

I am not facing this issue.

**Review by KKhushhalR2405 — APPROVED** [review]

**Comment by Muhammad-Galhoum** [comment]
@arpit456jain 

This is the same problem I had and I did this command "**python manage.py makemigrations home**"

And I put the **{%csrf_token%}** in my form, Try  to press **ctrl+f5** when you open the code in your browser to clear any cash

**Comment by Muhammad-Galhoum** [comment]
## @singhmansi25 
## Do you want me to make this change or wait for the opinion of @KKhushhalR2405 @arpit456jain @raghavTinker?

**Comment by KKhushhalR2405** [comment]
I think its a good idea  @Muhammad-Galhoum You can change it

**Comment by Muhammad-Galhoum** [comment]
## Sure, I will do it now  @KKhushhalR2405

**Comment by singhmansi25** [comment]
@Muhammad-Galhoum 
I guess u have missed the last line of the message.
Please update once.

**Comment by singhmansi25** [comment]
Otherwise its good to go.

**Comment by Muhammad-Galhoum** [comment]
## Changes have been made, can you review again
@singhmansi25

**Pull request merged**
