### PR TITLE
Prateek

### PR DESCRIPTION
**Pull request by prateekmohanty63**
Fixed all Sections URLS

All redirect working correctly now

### CODE REVIEW

**Comment by KKhushhalR2405** [comment]
Hi @prateekmohanty63  Few points from my side
1) Can you please mention the issue related to this PR
2) From next time, please try to change a few files in 1 PR. It is really tough to review so many files at once. And most of the changes you made are redundant, which we are about to change (have a look #163 ), though we appreciate your efforts 😊😊.

**Comment by KKhushhalR2405** [comment]
LGTM @arpit456jain

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM

**Comment by prateekmohanty63** [comment]
> Hi @prateekmohanty63 Few points from my side
> 
> 1. Can you please mention the issue related to this PR
> 2. From next time, please try to change a few files in 1 PR. It is really tough to review so many files at once. And most of the changes you made are redundant, which we are about to change (have a look [[Style] Add Template Inheritance #165](https://github.com/arpit456jain/CodingEasy/issues/165) ), though we appreciate your efforts 😊😊.

Yeah sure I will ensure that I write about the issue , next time
Actually when I ran the project in my local server I saw these redirecting urls not working , so I though of taking the issue up
By the way Thanks for your advice regarding best practices of sending pr :)  . @KKhushhalR2405

**Comment by arpit456jain** [comment]
@prateekmohanty63 ur issue was to correct only logo path 
#147 
but u have changed all the urls without informing us

some was working on this issue #166 

@KKhushhalR2405

**Comment by prateekmohanty63** [comment]
@arpit456jain  I have only corrected logo paths from all files, not changed any other urls.

**Comment by prateekmohanty63** [comment]
because all files logo redirect was not working properly

**Comment by arpit456jain** [comment]
@prateekmohanty63 for that we are working on template inheritance  for now i a, closing this PR 
when the template inheritance is done u can check urls if any of the url is wrong u can work on it

**Pull request closed without merging**
