### PR TITLE
[ADDED FEATURE] User Authentication System- Signin/Signup

### LINKED ISSUE #194: [FEATURE] User Authentication System- Signin/Signup
### Description

There is no user authentication system like sign in or sign out or sign up. I would like to create an authentication system in the backend with an inbuilt table 'auth_users'.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mr-palindrome**
## 🛠️ Fixes Issue
Closes #194 

## 👨‍💻 Changes proposed
Created new views for login, logout, and register for users using the inbuilt user model. Also changed navbar to add logout button if authenticated and changed login page to correct the register form.

## ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by KKhushhalR2405 — COMMENTED** [review]
Hi, @mr-palindrome Are you performing any form validation? If yes, how and where are you displaying the error messages if the form data is invalid?

**Comment by mr-palindrome** [comment]
> Hi, @mr-palindrome Are you performing any form validation? If yes, how and where are you displaying the error messages if the form data is invalid?

Yes, I'm using form validation for registering new users.
Whenever the form data is invalid like the username is already taken or the password is too short. I'm returning that in the form of a message to the template. And in the template, I just used simple jinja to render the message at the top of the page. 

I did not change the template that much.

**Comment by KKhushhalR2405** [comment]
I could not see the error messages. It just redirects to the same page whenever I submit invalid form data. Can you please check @mr-palindrome

**Comment by mr-palindrome** [comment]
> I could not see the error messages. It just redirects to the same page whenever I submit invalid form data. Can you please check @mr-palindrome

Now it is fixed. Can you please check again!!

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Sign up is not working if I am using any password less than 8 characters. It not showing eny error aswell

**Comment by mr-palindrome** [comment]
> Sign up is not working if I am using any password less than 8 characters. It not showing any error aswell

Now it should work fine!

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain

**Pull request merged**
