### PR TITLE
Adding reset password functionality

### PR DESCRIPTION
**Pull request by Muhammad-Galhoum**
### Don't forget to Allow this setting (Access the least secure apps )in your Gmail settings
[Access the least secure apps ](https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4PqwY-AQvHgAXaNp5ydcGu25c-nEBY9Ou_zekqOAA4tYSLXENFbRGJquYajuGd5Swy-5ZzX153Zv540J5NSsXfIDMYnCw)

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Muhammad-Galhoum** [comment]
### Please read the description in this repo very well
@arpit456jain @KKhushhalR2405

**Comment by singhmansi25** [comment]
@Muhammad-Galhoum 
The PR has conflicting files:
home/decorators.py
home/forms.py
home/urls.py
home/views.py
templates/home/Login/login.html
templates/includes/navbar.html

Please check into it.

**Comment by Muhammad-Galhoum** [comment]
**Are you reading the description in this repo very well ? @singhmansi25** 


### Very important note:- When I tried to clone the code for the following features login, signup and logout, I got many problems that has no solution, so I had to copy the code for these features and the other changes from the repo and paste them on my code, and finally I added (the password reset functionality) to my code, So don't worry All features of the website work correctly, All you can do test all features and merge the pull request
### Thanks in Advanced

### Don't forget to Allow this setting ([Access the least secure apps](https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4PqwY-AQvHgAXaNp5ydcGu25c-nEBY9Ou_zekqOAA4tYSLXENFbRGJquYajuGd5Swy-5ZzX153Zv540J5NSsXfIDMYnCw) )in your Gmail settings
 ### Access the least secure apps

### You can follow the instructions in this video [Password Reset Email](https://www.youtube.com/watch?v=sFPcd6myZrY&list=PL-51WBLyFTg2vW-_6XBoUpE7vpmoR3ztO&index=20&ab_channel=DennisIvy)

**Comment by Muhammad-Galhoum** [comment]
### I can delete the changes of these files which Nayan Das did from my code and add only the code of my task 
### Do you want this? @singhmansi25 @arpit456jain @KKhushhalR2405

**Comment by KKhushhalR2405** [comment]
You should add your part without altering someone else's. What problems are you facing. You can post it on our discord channel and we can discuss it there.

**Comment by arpit456jain** [comment]
@KKhushhalR2405 @singhmansi25 @raghavTinker

**Comment by raghavTinker** [comment]
Should I merge this PR @arpit456jain

**Comment by arpit456jain** [comment]
> Should I merge this PR @arpit456jain

Yes @raghavTinker we can merge it just waiting for at least 2 approvals from mentors

**Review by KKhushhalR2405 — APPROVED** [review]

**Comment by KKhushhalR2405** [comment]
LGTM @arpit456jain

**Pull request merged**
