### PR TITLE
Code editor

### PR DESCRIPTION
**Pull request by Vaishnavi1411**
## 🛠️ Fixes Issue

Added code editor.

## 👨‍💻 Changes proposed

Added button to link Editor.

## ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2022-04-05 000735

### CODE REVIEW

**Comment by Vaishnavi1411** [comment]
Review my PR @arpit456jain

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Well done

**Comment by singhmansi25** [comment]
@arpit456jain 
Please check this once

**Review by singhmansi25 — APPROVED** [review]

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
1) You have removed the Courses tab. Kindly re-add it.
2) Since the code editor is only for HTML/CSS currently, I would suggest you to add the button inside the HTML course page ( `templates/home/Html/html.html` )

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Please make the suggested changes ASAP.

**Comment by Vaishnavi1411** [comment]
Ok @singhmansi25

**Review by raghavTinker — APPROVED** [review]

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Have you made the proposed changes

**Comment by Vaishnavi1411** [comment]
Not yet!!

**Comment by singhmansi25** [comment]
Then try to complete this by end of this week @Vaishnavi1411

**Comment by arpit456jain** [comment]
@Vaishnavi1411 i had increased the label since its urgent so i am expecting to it done asap

**Comment by Vaishnavi1411** [comment]
ok @arpit456jain

**Comment by Vaishnavi1411** [comment]
I have to add an Editor on each card in image, style, table, etc.

**Comment by singhmansi25** [comment]
only main HTML page

**Comment by Vaishnavi1411** [comment]
Ok

**Comment by singhmansi25** [comment]
@Vaishnavi1411 
Update by tomorrow

**Comment by Vaishnavi1411** [comment]
Review my PR I have added a button on the HTML page
editor_html
.

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
