### PR TITLE
Added 2 videos of more than 10 mins on css including colors keywords and gradient topics

### PR DESCRIPTION
**Pull request by myhacktech**
L50:https://drive.google.com/file/d/1x1_fO-EInHdOnVlHHxVqDQtYSSyrShwe/view?usp=sharing
L51:https://drive.google.com/file/d/1LtJjEU5VeKqWFZbZjyRgYe0H5w8ENT29/view?usp=sharing
Screenshot (462)

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@myhacktech how many more topics are left according to you

**Comment by myhacktech** [comment]
@KKhushhalR2405 @singhmansi25 @arpit456jain please review this PR

**Comment by arpit456jain** [comment]
@myhacktech in next PR add all the rest videos instead of making multiple PR

**Comment by myhacktech** [comment]
> @myhacktech in next PR add all the rest videos instead of making multiple PR

ok sir

**Pull request merged**
