### PR TITLE
added 3 videos of approx. 15 mins on css

### PR DESCRIPTION
**Pull request by myhacktech**
L16:https://drive.google.com/file/d/1flMTuM0LuR2hD-P2g50DDOfUnJyMvTaS/view?usp=sharing
Screenshot (439)

L17:https://drive.google.com/file/d/1ch8TYan9_RrYMX-gnJU_FXsC9aQXHMR-/view?usp=sharing
L18:https://drive.google.com/file/d/1flMTuM0LuR2hD-P2g50DDOfUnJyMvTaS/view?usp=sharing

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by myhacktech** [comment]
@singhmansi25 i added 3 videos,so i expected level 3,please see

**Comment by myhacktech** [comment]
> @singhmansi25 i added 3 videos,so i expected level 3,please see

@arpit456jain

**Comment by singhmansi25** [comment]
@myhacktech 
The level is assigned on the basis of difficulty level of issues and contributions.
Still if @arpit456jain wants, he can assign you Level3.
Don't worry **:)**

**Review by singhmansi25 — APPROVED** [review]

**Comment by myhacktech** [comment]
> @myhacktech The level is assigned on the basis of difficulty level of issues and contributions. Still if @arpit456jain wants, he can assign you Level3. Don't worry **:)**

Ok

**Review by KKhushhalR2405 — APPROVED** [review]

**Pull request merged**
