### PR TITLE
Integrating One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course

### LINKED ISSUE #229: Integrating One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course
### Description

Integrating One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course
1. As the the html files are present but not connected to the machine learning course page I would like to connect them.
2.  Images of these files must be added to static folder.
3.  Images need to be connected with the files.
4.  Some UI changes have to be made such as extra list tags in the html files and extra quotes .
5. Images need to be added.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
## 🛠️ Fixes Issue

Closes #229

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Integrated One Hot Encoding, K-Fold Cross Validation and Grid Search modules to ML course

### CODE REVIEW

**Comment by Jayanth-MKV** [comment]
Please add the labels and review @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by Jayanth-MKV** [comment]
Please add the labels and review @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by arpit456jain** [comment]
@Jayanth-MKV share some ss of ur work it will help us to review faster

**Comment by Jayanth-MKV** [comment]
Screenshot (400)
Screenshot (401)
Screenshot (402)
Screenshot (403)

**Comment by Jayanth-MKV** [comment]
Added ss @arpit456jain

**Review by singhmansi25 — APPROVED** [review]
Please check @arpit456jain

**Pull request merged**
