### PR TITLE
Prateek

### PR DESCRIPTION
**Pull request by prateekmohanty63**
Added course video page
Navbar also added

### CODE REVIEW

**Comment by arpit456jain** [comment]
@prateekmohanty63 please share a video recording to demonstrate

**Comment by prateekmohanty63** [comment]
[https://drive.google.com/drive/folders/1-tQrx_9QOvLjjL_QyO0-_Dju0SvSNCvV?usp=sharing](url)

@arpit456jain  check it

**Comment by prateekmohanty63** [comment]
It was a pleasure @arpit456jain 
Thank you for the opportunity

**Comment by arpit456jain** [comment]
actually there is no models for contact us so do this.
1.move urls (only contact us for now) from Codingeasy project app to home app because we can't create models there
image

**Comment by arpit456jain** [comment]
And move its code from codingeasy.views to home.views

**Pull request merged**
