### PR TITLE
Completed the Blog Section

### LINKED ISSUE #139: [ENHANCEMENTS] Create a Proper Folder Architecture, a "Blogs" Section and Improving Authentication System.
**1. Create a Blogs Section -**
(a) Present users with insightful (concise yet powerful) blogs, which talk about various tech domains.
(b) Allow users to create, read, update and delete blog. Users other than author cannot delete the blogs.
(c) Authors can have their profile pics on the blog preview card. Clicking on it leads to their Profile on the website.

**2. Improve Authentication System and Contact Us Section -** 
(a) Use “Crispy forms” for user registration instead of the current authentication layout. Crispy Forms uses bootstrap as default styling engine, which will lead to more uniformity in the website (as opposed to the current case; login/signup and contact us pages are quite buggy). 
(b) Same applies for the Contact Us section.

I have the required experience for incorporating above stated enhancements. Could you please assign this task to me? 
Thank you.

### PR DESCRIPTION
**Pull request by ephemeralshay**
## 🛠️ Fixes Issue
Closes #139 

## 📄 Note to reviewers
1. Profile Section for users was added
2. Users can write and delete their blogs. They can only view others blog.
3. Blog and Profile section can be seen only when user is logged in.

### CODE REVIEW

**Comment by ephemeralshay** [comment]
@arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker Please the review the PR

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
image
Please remove the option for login when the user is already logged in

**Comment by arpit456jain** [comment]
@ephemeralshay

**Comment by ephemeralshay** [comment]
Done @KKhushhalR2405 @arpit456jain

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM @arpit456jain

**Comment by singhmansi25** [comment]
@ephemeralshay 
Have you added option to add and make changes to blogs?
I wasn't able to see it.
As on clicking Blog Page, I get default not found page

**Comment by ephemeralshay** [comment]
@singhmansi25 the blog is fully working with CRUD operation

**Comment by singhmansi25** [comment]
Can you share some ss ? @ephemeralshay

**Comment by ephemeralshay** [comment]
Okay, will do that in half an hour

**Comment by ephemeralshay** [comment]
Okay, after half an hour

**Comment by ephemeralshay** [comment]
@singhmansi25 Please check discord. Detailed screenshots have been attached.

**Review by singhmansi25 — APPROVED** [review]
@ephemeralshay 
I appreciate your work and efforts.
**Congratulations**

**Comment by arpit456jain** [comment]
great work @ephemeralshay

**Review by arpit456jain — APPROVED** [review]

**Comment by ephemeralshay** [comment]
Thanks a lot 🙌

**Pull request merged**
