### PR TITLE
implement a download csv feature in admin panel for downloading the data as csv file

### LINKED ISSUE #91: implement a download csv feature in admin panel for downloading the data as csv file

### PR DESCRIPTION
**Pull request by harikishantk**
Closes #91

### CODE REVIEW

**Comment by arpit456jain** [comment]
@harikishantk please share a demo video to show us how its working

**Comment by 7saikat7** [comment]
please provide a SS of this from admin panel

**Comment by harikishantk** [comment]
> please provide a SS of this from admin panel

https://github.com/arpit456jain/CodingEasy/issues/91#issuecomment-1022204885 @7saikat7

**Comment by arpit456jain** [comment]
cool @harikishantk  its working fine 
just do one thing the code which is commented , remove the code from comment its fine

**Comment by harikishantk** [comment]
@arpit456jain done :smile:

**Comment by arpit456jain** [comment]
@harikishantk can you please msg me on discord asap

**Comment by harikishantk** [comment]
@arpit456jain done

**Pull request merged**
