### PR TITLE
Showing the username in the navbar with welcome message and changing the navbar style to be more attractive

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Muhammad-Galhoum** [comment]
### I have changed the navbar shape and style so, I get conflict with the last navbar code, what should I do? 
**@arpit456jain @KKhushhalR2405 @singhmansi25 @raghavTinker** 

navbar

**Comment by muhammadgalhoum** [comment]
Already I did this, but this conflict is because I change all the code for the navbar so I get conflict the last code 
Tell me what should I do? @KKhushhalR2405

**Comment by muhammadgalhoum** [comment]
I checked the checkbox for this option in my pull request **Allow edits by maintainers** so if you can help me please help me

**My task #207** is to change the navbar to be attractive and beautiful and show the username of the person who logged in

**Comment by singhmansi25** [comment]
@muhammadgalhoum 
There is one conflict here: templates/includes/navbar.html

resolve this please

**Comment by muhammadgalhoum** [comment]
This conflict is because I have changed all the code for the navbar so I get conflict with the last code for the navbar
Tell me what should I do? @singhmansi25

**Comment by muhammadgalhoum** [comment]
**I have solved the conflict, please review my code** 

@singhmansi25 @KKhushhalR2405 @raghavTinker @arpit456jain

**Comment by arpit456jain** [comment]
@muhammadgalhoum i have merged one PR just now can u please solve this merge conflicts again
sorry for inconvenience

**Comment by muhammadgalhoum** [comment]
I have solved the conflict @arpit456jain

**Comment by singhmansi25** [comment]
@arpit456jain 
Please review this again.

**Pull request merged**
