### PR TITLE
LeetCode Videos

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review @arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by muhammadgalhoum** [comment]
@arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker 
https://user-images.githubusercontent.com/56798376/171146351-a3ddb87b-973d-4a80-b0ea-0c6302ef6aaa.mp4

**Comment by muhammadgalhoum** [comment]
@arpit456jain @singhmansi25 @KKhushhalR2405 @raghavTinker

**Comment by arpit456jain** [comment]
great work @muhammadgalhoum 

1.instead of adding leetcode in navbar make a card just like other courses 

2. i am thinking to add the text solution also can u do that ?

**Comment by muhammadgalhoum** [comment]
> great work @muhammadgalhoum
> 
> 1.instead of adding leetcode in navbar make a card just like other courses
> 
> 2. i am thinking to add the text solution also can u do that ?

Thanks, @arpit456jain
 
Please give me Level 3 for this work

Can u explain more what u mean by this sentence "instead of adding leetcode in navbar make a card just like other courses"

**Comment by arpit456jain** [comment]
> > great work @muhammadgalhoum
> > 1.instead of adding leetcode in navbar make a card just like other courses
> > 
> > 2. i am thinking to add the text solution also can u do that ?
> 
> Thanks, @arpit456jain
> 
> Please give me Level 3 for this work
> 
> Can u explain more what u mean by this sentence "instead of adding leetcode in navbar make a card just like other courses"

sure

**Comment by muhammadgalhoum** [comment]
> 2\. i am thinking to add the text solution also can u do that ?

I think that if the user finds the solution on the site, he will not open the videos, so it is better that you put the solution in the description of the video on YouTube, and that leads to making the user watch the video and the solution

**Pull request merged**
