### PR TITLE
Adding Side Navigation Bar

### PR DESCRIPTION
**Pull request by BabyElias**
Closes part of #253 

## 👨‍💻 Changes proposed

Created an external CSS file for side navigation bar.<br>
Added the CSS file to header template.<br>
Fixed top navbar.<br>
Made changes to html.html file Only(the HTML course homepage)

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
Side nav is overlapping the entire page.
image

**Comment by BabyElias** [comment]
Now, please check @KKhushhalR2405. Looks like this in my system. Why is the logo green in color btw?
image

**Comment by KKhushhalR2405** [comment]
It's still the same for me, the navbar overlapping the entire page. @arpit456jain @raghavTinker @singhmansi25 can you guys please confirm

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/167394267-011aa8b7-cdb4-4ce2-ab7b-23113e375b0d.mp4

yes @KKhushhalR2405  its same for me

@BabyElias  its overlapping and its only present in one page kindly look into it

**Comment by BabyElias** [comment]
Looking into it ,though I can't find any reasons right now why it might fail this way :(

**Comment by BabyElias** [comment]
@arpit456jain Is the website in the video same as the one deployed on Heroku? Any way that I can inspect the contents of the site that you have recorded would be really appreciated.

**Comment by arpit456jain** [comment]
> @arpit456jain Is the website in the video same as the one deployed on Heroku? Any way that I can inspect the contents of the site that you have recorded would be really appreciated.

@BabyElias  do one this host ur branch on heroku lets see if that works or not  or lets have a meet u can use my PC by anydesk

**Comment by BabyElias** [comment]
@arpit456jain can you just share the css file related to the top navbar, I think I have figured it out.

**Comment by arpit456jain** [comment]
> @arpit456jain can you just share the css file related to the top navbar, I think I have figured it out.

@BabyElias dm me and lets have a meet

**Comment by arpit456jain** [comment]
@BabyElias

**Comment by BabyElias** [comment]
@arpit456jain Wouldn't be able to work on the project till Monday as my Laptop has gone for repair. Sorry for not replying before, I thought the problem with my laptop was minor and I would respond once it's done :(

**Comment by arpit456jain** [comment]
ok

**Pull request closed without merging**
