### PR TITLE
A separate page for listing our templates and downloading them #234

### LINKED ISSUE #234: A separate page for listing our templates and downloading them
### Description

I have 3 repos 
[Cool Front-End Templates](https://github.com/arpit456jain/Cool-Front-End_Templates)
[Amazing Css effects](https://github.com/arpit456jain/Amazing-Css-Effects)
[Amazing Js Projects](https://github.com/arpit456jain/Amazing-Js-Projects)

i want to fetch all the projects and list them here with a feature of downloading it
It should download the source code if template in zip file directly 

ping me discord server if any confusion because it might be confusing 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
## 🛠️ Fixes Issue

Closes #234  

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

almost the major things have been done and the rest will be done in subsequent prs. Once this is finalized i will proceed with the other templates as well.
Screenshot (426)
Screenshot (425)

### CODE REVIEW

**Comment by Jayanth-MKV** [comment]
Review @KKhushhalR2405 @singhmansi25 @arpit456jain @raghavTinker

**Comment by arpit456jain** [comment]
@Jayanth-MKV really a great work 

just add a option in navbar 

templates

so that anyone can go to that page easily

**Comment by Jayanth-MKV** [comment]
#Done @arpit456jain

**Comment by arpit456jain** [comment]
check #269 @Jayanth-MKV

**Pull request merged**
