### PR TITLE
Updating Python Course and adding four new lessons 

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## 🛠️ Fixes Issue #306  

# The four new lessons are

- Functional Programming
- Exception
- OOP
- Working with Strings

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review @arpit456jain  @KKhushhalR2405 @singhmansi25 @raghavTinker

**Review by singhmansi25 — APPROVED** [review]
@muhammadgalhoum 
In exceptions.html: Please highlight the common exceptions name, so that someone can easily refer it.
Otherwise its alright.

**Comment by muhammadgalhoum** [comment]
I have made the required changes @singhmansi25

**Review by singhmansi25 — COMMENTED** [review]
@muhammadgalhoum 
I guess I was not able to explain you clearly. 
Please make this para :
Different exceptions are raised for different reasons.
Common exceptions:
**ImportError:** an import fails;
**IndexError:** a list is indexed with an out-of-range number;
**NameError:** an unknown variable is used;
**SyntaxError:** the code can't be parsed properly;
**TypeError:** a function is called on a value of an inappropriate type;
**ValueError:** a function is called on a value of the correct type, but with an inappropriate value.

Please bold the names of errors, so its easy to check.

**Comment by muhammadgalhoum** [comment]
Please review again @singhmansi25

**Review by raghavTinker — APPROVED** [review]

**Comment by muhammadgalhoum** [comment]
Please, merge this PR @arpit456jain

**Pull request merged**
