### PR TITLE
Added SWOC LOGO 

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #22

Hey @arpit456jain 
Please Review

### CODE REVIEW

**Comment by arpit456jain** [comment]
sa
 use this

**Comment by Atif0604** [comment]
Ok

**Comment by Atif0604** [comment]
Done @arpit456jain

**Comment by arpit456jain** [comment]
move it to top please @Atif0604 and tag mentor @ankitapuri  for reviewing the PR from now onwards

**Comment by Atif0604** [comment]
> move it to top please @Atif0604 and tag mentor @ankitapuri for reviewing the PR from now onwards

Ok Sure

**Comment by Atif0604** [comment]
hey @ankitapuri Please review

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
