### PR TITLE
Adding Git course 

### LINKED ISSUE #232: Adding Git course
### Description

Although the git_github files are available they are not connected with the website

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Jayanth-MKV**
Screenshot (407)
Screenshot (408)
Screenshot (409)

Closes #232

## 👨‍💻 Changes proposed
Added git and Github course

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Jayanth-MKV** [comment]
review and label @arpit456jain @singhmansi25 @KKhushhalR2405

**Review by singhmansi25 — CHANGES_REQUESTED** [review]
@Jayanth-MKV 
Please correct the content of grey box and centerline the heading. Also Simply change heading to "Git & Github"
Follow same font size in side grey box. Follow proper indentation for Installation of GUI, i.e, give proper spacing before and after links. 
Rename Installation & GUIS to simple : Installation
And if possible place the card of Git and Github properly.
Make these changes and create PR.

**Comment by Jayanth-MKV** [comment]
The mentioned changes are made. @singhmansi25 
Review

Screenshot (409)

Screenshot (411)

**Comment by singhmansi25** [comment]
@Jayanth-MKV 
Please do centerline the heading.

**Comment by Jayanth-MKV** [comment]
@singhmansi25 But all the other courses have the heading aligned to the left

**Comment by Jayanth-MKV** [comment]
@singhmansi25 If you confirm I will make it

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
