### PR TITLE
Embedded Python IDE

### PR DESCRIPTION
**Pull request by nikhil25803**
## 👨‍💻 Changes proposed

This Pull Request is regarding issue #291 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have embedded Python Replit IDE in the Functions, Loops, Conditional, and File Handling page.

## 📷 Screenshots
[image](https://www.linkpicture.com/view.php?img=LPic62780c4b80e7a2142772534)

### CODE REVIEW

**Comment by nikhil25803** [comment]
@raghavTinker @KKhushhalR2405 @singhmansi25 .... Do review it once pls!

**Review by raghavTinker — APPROVED** [review]

**Review by KKhushhalR2405 — CHANGES_REQUESTED** [review]
I would suggest, adding ide to all python pages just to maintain evenness. The rest looks good. Good work @nikhil25803

**Comment by nikhil25803** [comment]
@KKhushhalR2405 ,
@arpit456jain Bhaiya asked me to add it in a few pages only, that's why I added it in 4 pages only :(

**Comment by arpit456jain** [comment]
> @KKhushhalR2405 , @arpit456jain Bhaiya asked me to add it in a few pages only, that's why I added it in 4 pages only :(

Yes when this PR gets merged then add it to all other pages

Btw attach a video for showing how the python code is running in ide

**Review by KKhushhalR2405 — APPROVED** [review]

**Comment by nikhil25803** [comment]
Okay!
Will try to make a video after adding IDE to all pages.

**Comment by arpit456jain** [comment]
@nikhil25803 now add this in all pages of python

**Comment by nikhil25803** [comment]
> @nikhil25803 now add this in all pages of python

Okay :)

**Pull request merged**
